VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "DataTransferRepository"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Compare Database
Option Explicit

'''
'外部ファイルを読込み、 Access テーブルへ登録する。
'
'@param objModel 入力元と出力先の情報を格納したモデルオブジェクトを指定する。
'''
Public Sub importData(objModel As Object)

End Sub

'''
'Access テーブルのデータを外部ファイルへ出力する。
'
'@param objModel 入力元と出力先の情報を格納したモデルオブジェクトを指定する。
'''
Public Sub exportData(objModel As Object)

End Sub
